# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KvitokApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapistable',
            name='description',
            field=models.TextField(default='', verbose_name='Примечание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zapistable',
            name='ffrom',
            field=models.CharField(default=' ', max_length=50, verbose_name='От кого'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zapistable',
            name='invent_number',
            field=models.CharField(default='', max_length=50, verbose_name='Инвентарный номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zapistable',
            name='ipaddr',
            field=models.CharField(default='', max_length=50, verbose_name='Ip адресс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zapistable',
            name='name_host',
            field=models.CharField(default='', max_length=50, verbose_name='Имя хоста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zapistable',
            name='to',
            field=models.CharField(default='', max_length=50, verbose_name='Кому'),
            preserve_default=False,
        ),
    ]
